#!/usr/bin/env zsh

# PROJECT SWITCHER: VERSION V1
# This is a bash script to save and change directories. The usage is at the bottom. Two things to keep in mind.
# - The saved directories are saved in "$HOME/.local/share/project_swapper/.saved_dirs"
# - There are also a alias in the .zshrc file that says pro=". pro". The pro command get launched as source script so that it can change direcotries

mkdir -p "$HOME/.local/share/project_swapper/"
touch "$HOME/.local/share/project_swapper/.saved_dirs"

saved_dirs="$HOME/.local/share/project_swapper/.saved_dirs"

if [[ "$1" == "save" ]]; then
    pwd >> $saved_dirs
    echo "Saved currect directory."
elif [[ "$1" == "list" ]]; then
    LINE=1
    while read -r CURRENT_LINE
        do
            echo "$LINE: $CURRENT_LINE"
        ((LINE++))
    done < "$saved_dirs"
elif [[ "$1" =~ ^[0-9]+$ ]]; then
    dir=$(sed -n "$1p" $saved_dirs)
    if [[ -d "$dir" ]]; then
        cd "$dir"
        clear
    else
        echo "Directory not found"
    fi
elif [[ "$1" == "del" ]]; then
    $(sed -i .bak "$2d" $saved_dirs)
else 
    echo "Usage: pjs [<number>|del <number>|save|list]"
fi
